<<<<<<< HEAD
[build]
  command = "npm install && npm run build"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-functions-core"
=======
[build]
  command = "npm install && npm run build"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-functions-core"
>>>>>>> 73b0212facf5a3f142687133f972cf95ab542f23
